---

name: Documentation

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - '**.md'
  pull_request:
    branches: [main]
    paths:
      - '**.md'

jobs:
  quality:
    name: Quality checks
    runs-on: [ubuntu-latest]

    steps:
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '8.1'
          tools: composer:v2
          extensions: intl, mbstring, xml

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Lint markdown files
        uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: .
          ignore_path: .markdownlintignore
